[meta]
  title = "Flask Live ChatGPT Text-to-Speech Starter"
  description = "Get started using Deepgram's Live ChatGPT Text-to-Speech with this Flask demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "TTS"
  language = "Python"
  framework = "Flask"

[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `python app.py` to get up and running."
